meta_product_name: "Prêt-à-brasser"
meta_title: "Prêt-à-brasser - Soyez sur de réussir vos premières bières !"
meta_description: "Prêt-à-Brasser vous accompagne dans vos premiers brassin en vous proposant un accompagnement complet pour mettre toutes les chances de votre coté et déguster une vraie bonne Craft DIY !"
meta_image: "cover.png" # should exist in `app/assets/images/`
